'use client'
import { Header } from '@/components/Header'
import Globalstyles from '@/themes/globalstyles'
import StyledComponentsRegistry from '@/themes/registry'
import { dark, light } from '@/themes/theme'
import usePeristedState from '@/utils/usePersistedState'

import { ReactNode } from 'react'
import { DefaultTheme, ThemeProvider } from 'styled-components'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  const [theme, setTheme] = usePeristedState<DefaultTheme>('theme', light)
  const toggleTheme = () => {
    setTheme(theme.title === 'light' ? dark : light)
  }

  console.log(theme.colors, 'theme')
  return (
    <ThemeProvider theme={theme}>
      <Globalstyles />
      <html lang="en">
        <body>
          <Header toggleTheme={toggleTheme} theme={theme.title} />
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </body>
      </html>
    </ThemeProvider>
  )
}
